server:
  # 本地接口服务
   test: http://127.0.0.1:8888/
  # https://space.bilibili.com/283273603 演示项目后端服务来自
#   dev: http://192.168.31.11:8080/backend/
   dev: http://192.168.0.6/api/

# 基准的请求头信息
request_headers:
  Accept-Encoding: gzip, deflate
  Accept-Language: zh-CN,zh;q=0.9
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

# 用例及报告位置
file_path:
#  test_case: data/case_data.xls
  test_case: data/613_case_data.xls
  report: report/
  log: log/run{time} log

email:
  # 发件人邮箱
  user:  302559651@qq.com
  # 发件人邮箱授权码
  password:  gnwzuldkeobpbjdh
  # 邮箱host
  host:  smtp.qq.com
  contents:  解压apiAutoReport.zip(接口测试报告)后，请使用已安装Live Server 插件的VsCode，打开解压目录下的index.html查看报告
  # 收件人邮箱
  addressees:  ["chenlei305@qq.com"]
  title:  接口自动化测试报告(见附件)
  # 附件
  enclosures: report.zip

# 数据库校验- mysql
database:
  host: 192.168.31.10
  port: 3306
  user: root
  # 不用''会被解析成int类型数据
  password: 'password'
  db_name:  apiautotest
  charset:  utf8mb4

  # 数据库所在的服务器配置
  ssh_server:
    port: 22
    username: root
    password: 'password'
    # 私有密钥文件路径
    private_key_file:
    # 私钥密码
    privat_passowrd:
    # 如果使用的docker容器部署mysql服务，需要传入mysql的容器id/name
    mysql_container: mysql8
    # 数据库备份文件导出的本地路径, 需要保证存在该文件夹
    sql_data_file: backup_sqls/




